SSN/SSN/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('account/', include('account.urls', namespace='account')),
]

SSN/account/urls.py
from django.urls import path
from .views import user_login, user_logout, user_register

app_name = 'account'
urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('register/', user_register, name='user_register'),
]

SSN/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.posts_list_view, name='all-posts'),
    path('post-detail/<int:pk>', views.post_detail, name='post-detail'),
]

SSN/account/models.py
from django.db import models

# Create your models here.

SSN/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    slug = models.SlugField(max_length=200)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user}, {self.body[:30]}'

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'pk': self.id})

SSN/account/forms.py
from django import forms


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                             'placeholder': 'your username'}))
    password = forms.CharField(max_length=255, widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                 'placeholder': 'your password'}))


class UserRegisterForm(forms.Form):
    username = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                             'placeholder': 'your username'}))
    password = forms.CharField(max_length=255, widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                 'placeholder': 'your password'}))
    email = forms.EmailField(max_length=255, widget=forms.EmailInput(attrs={'class': 'form-control',
                                                                            'placeholder': 'your email'}))

SSN/account/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegisterForm
from django.contrib import messages


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd['username']
            password = cd['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'You logged in successfully', 'success')
                return redirect('posts:all-posts')
            else:
                messages.warning(request, 'username OR password is wrong! Try again.', 'danger')
    else:
        form = UserLoginForm()
        return render(request, 'account/login.html', {'form': form})


def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, 'you logged out successfully', 'success')
        return redirect('posts:all-posts')


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            user = User.objects.create_user(username, email, password)
            messages.success(request, 'You registered successfully', 'success')
            login(request, user)
            return redirect('posts:all-posts')

    else:
        form = UserRegisterForm()
        return render(request, 'account/register.html', {'form': form})

SSN/posts/views.py
from django.shortcuts import render
from .models import Post


def posts_list_view(request):
    all_posts = Post.objects.all()
    return render(request, 'posts/all_posts.html', {'all_posts': all_posts})


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'posts/post_details.html', {'post': post})

SSN/posts/templates/posts/all_posts.html
{% extends 'base.html' %}

{% block title %} All Post View {% endblock %}

{% block main_content %}
    {% for post in all_posts %}
        <p class="card-header">
            {{ post.user }} | {{ post.created|date }}
        </p>
        <p class="card-body">
            <a href="{{ post.get_absolute_url }}">
                {{ post.body }}
            </a>
        </p>
    {% endfor %}
{% endblock %}

SSN/posts/templates/posts/post_details.html
{% extends 'base.html' %}

{% block title %} Detail Page for {{ page.id }} {% endblock %}

{% block main_content %}
    <p class="card-header">
        {{ post.user }} | {{ post.created|date }}
    </p>
    <p class="card-body">
        {{ post.body }}
    </p>
    <a class="btn btn-outline-primary" href="{% url 'posts:all-posts' %}"> Back </a>
{% endblock %}

SSN/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}Main Page{% endblock %}
    </title>
    {% block css %}
        <link href="{%  static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    {% endblock %}
</head>
<body>

{% include 'inc/navbar.html' %}
<div class="container">
    <div class="card">
        {% include 'inc/messages.html' %}
        {% block main_content %}{% endblock %}
    </div>
</div>
</body>
</html>

SSN/templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>
    {% endfor %}
{% endif %}

SSN/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'posts:all-posts' %}">Home</a>
          {% if request.user.is_authenticated %}
              <a class="nav-link active" href="{% url 'account:user_logout' %}">Logout</a>
          {% else %}
              <a class="nav-link active" href="{% url 'account:user_login' %}">Login</a>
              <a class="nav-link active" href="{% url 'account:user_register' %}">Register</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>